name: Playwright Tests
on:
  issue_comment:                                     
    types: 
    - created
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.19
    if: contains(github.event.comment.body, '/playwright')
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run Playwright tests
      run: bunx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
